version: "3"

services:
  postgresql:
    image: postgres:15
    volumes:
      - ./migrations:/database/data
    environment:
      POSTGRES_USER: Enkognit
      POSTGRES_PASSWORD: 228
      POSTGRES_DB: scrapper
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=Enkognit
      - --password=228
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
networks:
  backend: